# Setting palette
palette = "gruvbox_dark"

[aws]
style = "bold orange"

[azure]
style = "bold blue"

[character]
error_symbol = "[JAMMERJOH](bold red)"
success_symbol = "[λ](bold green)"

[cmd_duration]
style = "bold yellow"

[directory]
style = "bold green"

[git_branch]
style = "bold purple"

[git_status]
style = "bold red"

[terraform]
disabled = true

[palettes.gruvbox_dark]
color_fg0 = '#fbf1c7'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'